# Generated by Django 4.2.4 on 2023-08-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('release_date', models.DateField()),
                ('slug', models.SlugField(max_length=30)),
            ],
        ),
    ]
